---
- name: Gather minimal facts to determine OS family
  setup:
    gather_subset:
      - '!all'
      - 'min'
  tags: [install_sudo, os_check, system_preparation]
- name: Install sudo on Debian-based systems if missing
  apt:
    name: sudo
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'
  tags: [install_sudo, os_check, system_preparation]

- name: Log that sudo is managed via 'wheel' on RHEL-based systems
  debug:
    msg: "'sudo' not required explicitly on RHEL — users should be added to the 'wheel' group."
  when: ansible_facts['os_family'] == 'RedHat'
  tags: [install_sudo, os_check, system_preparation]
