---
- name: Read public key from control node
  delegate_to: localhost
  run_once: true
  slurp:
    src: "{{ public_key_file }}"
  register: pubkey_raw
  tags: 
    - initial_authentication_setup
    - system_preparation

- name: Set decoded public key content
  set_fact:
    pubkey_decoded: "{{ pubkey_raw.content | b64decode | trim }}"
  tags:
    - initial_authentication_setup
    - system_preparation

- name: Ensure /root/.ssh directory exists on remote host
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '0700'
  tags:
    - initial_authentication_setup
    - system_preparation

- name: Ensure public key is added to /root/.ssh/authorized_keys if not already present
  lineinfile:
    path: /root/.ssh/authorized_keys
    create: yes
    line: "{{ pubkey_decoded }}"
    owner: root
    group: root
    mode: '0600'
    state: present
  tags:
    - initial_authentication_setup
    - system_preparation

