---
#************* Initial Authentication and configurations  *******************#

- name: Include initial authentication setup
  include_tasks: initial_authentication_setup.yml
  tags: [initial_authentication_setup, system_preparation]

- name: Include sudo installation and OS check
  include_tasks: check_and_install_sudo.yml
  tags: [install_sudo, os_check, system_preparation]

- name: Include ansible_deployments user creation
  include_tasks: create_ansible_user.yml
  tags: [create_ansible_user, user_setup, system_preparation]

- name: Include public key setup for ansible_deployments user
  include_tasks: push_key.yml
  tags: [setup_ansible_user_key, system_preparation]

#************* User Management and Configurations  *******************#
- name: create user
  include_tasks: enterprise_user_management.yml
  tags:
    - user_management
    - enterprise
    - users
    - security
- import_tasks: team_user_management.yml
  tags: [user_mgmt]

#************* Tang and Clevis for VM Drive Encryption/Decryption  *******************#

- name: Include Clevis installation tasks
  include_tasks: disk_and_mount_setup.yml
  tags: [install_clevis_luks_initramfs, system_preparation]

- name: Include Tang binding and GRUB setup
  include_tasks: automated_tang_binding_grub_network.yml
  tags: [tang_grub, grub_config, cleanup, system_preparation]

#************* ll Command Fix  *******************#

- name: Perform system preparation and install basic tools
  import_tasks: shell_alias.yml
  tags: [shell_alias, system_preparation]

#************* All Basic Tools Installations *******************#

- name: Include basic tools installation tasks
  include_tasks: basic_tools_installations.yml
  tags: [basic_tools_installations, system_preparation]

#************* E21 - Debain nftables Installatin and Configurations  *******************#

- name: Configure dynamic nftables firewall
  include_tasks: nftables_install_config.yml
  tags: [nftables, firewall, security]

    #tags: [nftables, nftables_install, nft_main_dir, nft_rules_dir, nft_sets_dir, nft_ssh, ssh_ip_whitelist, system_preparation]

#************* Fail2ban Installation and configurations  *******************#

- name: Include fail2ban installation configuration and copy tasks
  include_tasks: fail2ban_install_config.yml
  tags: [install_fail2ban, copy_jail_local_fail2ban, enable_start_fail2ban, system_preparation]

#************* SSH Hardening - Copy Optimized File  *******************#

- name: Include SSH hardening tasks
  include_tasks: ssh_hardening.yml
  tags: [ssh_hardening, system_preparation]

#************* Logging and Monitoring of the VM on Server  *******************#

- name: Include Installation for logging
  include_tasks: logging_monitoring.yml
  tags: [snoopy_auditd_logging_monitoring, system_preparation]

#************* Installation of Nginx with Nginx Repo - Stable Version  *******************#

- name: Include task to install nginx if not already present
  ansible.builtin.include_tasks: install_nginx.yml
  tags: [install_nginx, webserver, system_preparation]

#************* Installation of dotnet Packages 8.0 and 9.0  *******************#

- name: Include task to install .NET SDKs
  ansible.builtin.include_tasks: install_dotnet.yml
  tags: [install_dotnet, system_preparation]

#************* Default and Mandatory Group creation and Sudoers Restrictions  *******************#

- name: Include log editing restriction setup
  include_tasks: restrict_log_editing.yml
  tags: [deny-logs-editing, system_preparation]

- name: Include sudo permissions for all-users-allowtroubleshooting group
  include_tasks: allow-troubleshooting.yml
  tags: [allow-troubleshooting, system_preparation]

- name: Include sudo permissions for all-users-allow-logs-access group
  include_tasks: all-users-allowlogsaccess.yml
  tags: [allow-logs-access, system_preparation]

#************* ACL Installation  *******************#

- name: Include ACL and inotify-tools installation
  include_tasks: install_acl_inotify.yml
  tags: [acl_installation, system_preparation]

#************* DB Group Creation and Appropriate Sudo Permissions   *******************#

- name: Include vwdb-ldba sudo permissions
  include_tasks: vwdb_ldba_sudoers.yml
  tags: [vwdb-ldba-sudoers, system_preparation]

- name: Include DB ACL Setup Tasks
  import_tasks: vwdb_ldba_acl_setup.yml
  tags: [db_acl_implementation, system_preparation]

#************* dotnet Group Creation and Appropriate Sudo Permissions   *******************#

- name: Include sudo permissions for vwdev-ldnet
  include_tasks: vwdev_ldnet_sudoers.yml
  tags: [vwdev-ldnet-sudoers, system_preparation]

- name: Include vwdev-ldnet ACL Setup
  include_tasks: vwdev_ldnet_acl_setup.yml
  tags: [vwdev-ldnet-sudoers, vwdev-ldnet_acl_implementation, system_preparation]

#************* Python Group Creation and Appropriate Sudo Permissions   *******************#

- name: Include sudo permissions for vwdev-lpyt
  include_tasks: vwdev_lpyt_sudoers.yml
  tags: [vwdev_lpyt-sudoers, system_preparation]

- name: Include vwdev-lpyt ACL Setup
  include_tasks: vwdev_lpyt_acl_setup.yml
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

#************* TAC Group Creation and Appropriate Sudo Permissions   *******************#

- name: Include sudo permissions for vwdev-lpyt
  include_tasks: vwtac_ltac_sudoers.yml
  tags: [vwtac_ltac-sudoers, system_preparation]

- name: Include vwdev-lpyt ACL Setup
  include_tasks: vwtac_ltac_acl_setup.yml
  tags: [vwtac_ltac-sudoers, vwtac_ltac_acl_implementation, system_preparation]

#************* Script and Service Creation and Appropriate Permissions according to the Requirements   *******************#

- name: Include task to generate mysql ownership script
  ansible.builtin.include_tasks: fix_ownership_script.yml
  tags: [script_directory, fix_mysql_ownership, mysql_ownership_script_setup, fix_postgres_ownership, postgres_ownership_script_setup, fix_nginx_dnet_ownership, nginx_dnet_ownership_script_setup, fix_nginx_pyt_ownership, nginx_pyt_ownership_script_setup, system_preparation]

- name: Include task to generate mysql ownership script service
  ansible.builtin.include_tasks: fix_ownership_service.yml
  tags: [daemon_reload_man, fix_postgres_ownership, fix_mysql_ownership, fix_nginx_dnet_ownership, fix_nginx_pyt_ownership, postgres_ownership_service_setup, mysql_ownership_service_setup, nginx_dnet_ownership_service_setup, nginx_pyt_ownership_service_setup, system_preparation]

#************* Dotnet Service - Script and Webserver Configurations   *******************#

#dotnet_nginx_se_sc.yml
- name: Include directory creation tasks
  include_tasks: dotnet_nginx_se_sc.yml
  tags: [directories, dotnet_nginx_config, system_preparation]

#************* Python Service - Script and Webserver Configurations *******************#

- name: Setup Python Environment
  import_tasks: setup_python_env.yml
  tags: [install_python_packages, directories, deploy_service_script, python_service_setup, python_env_setup, system_preparation, python_service_setup]

