- name: Ensure group 'vwdev-lphp' exists
  group:
    name: "vwdev-lphp"
    state: present
  tags:
    - vwdev-lphp-sudoers
    - system_preparation

- name: Deploy sudoers template for 'vwdev-lphp'
  template:
    src: "vwdev-lphp.j2"
    dest: "/etc/sudoers.d/vwdev-lphp"
    owner: root
    group: root
    mode: '0440'
    validate: '/usr/sbin/visudo -cf %s'
  tags:
    - vwdev-lphp-sudoers
    - system_preparation

