- name: Ensure dev_directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0775'
    recurse: yes
  loop: "{{ dev_directories }}"
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation


- name: Change ownership recursively to nginx:nginx
  command: chown -R nginx:nginx {{ item }}
  loop: "{{ dev_directories }}"
  register: chown_dirs
  failed_when: false
  ignore_errors: true
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Change permissions recursively to 755
  command: chmod -R 755 {{ item }}
  loop: "{{ dev_directories }}"
  register: chmod_dirs
  failed_when: false
  ignore_errors: true
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation


- name: Set ACL rwx recursively on directories
  command: setfacl -R -m g:{{ dev_group_dont_net }}:rwx {{ item }}
  loop: "{{ dev_directories }}"
  register: acl_dirs
  failed_when: false
  ignore_errors: true
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Set default ACL rwx on directories (for future files/folders)
  command: setfacl -dR -m g:{{ dev_group_dont_net }}:rwx {{ item }}
  loop: "{{ dev_directories }}"
  register: default_acl_dirs
  failed_when: false
  ignore_errors: true
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Set ACL rwx on individual files (optional)
  when: dev_files is defined and dev_files | length > 0
  command: setfacl -m g:{{ dev_group_dont_net }}:rwx {{ item }}
  loop: "{{ dev_files }}"
  register: acl_files
  failed_when: false
  ignore_errors: true
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Display results for directories ACL set
  debug:
    msg: "Directory ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ acl_dirs.results }}"
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Display results for directories default ACL set
  debug:
    msg: "Default ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ default_acl_dirs.results }}"
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

- name: Display results for file ACL set
  when: dev_files is defined and dev_files | length > 0
  debug:
    msg: "File ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ acl_files.results }}"
  tags:
    - vwdev-ldnet_acl_implementation
    - system_preparation

