- name: Ensure dev_pyt_directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ dev_pyt_directories }}"
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation] 

- name: Set ACL rwx recursively on directories
  command: setfacl -R -m g:{{ dev_group_pyt }}:rwx {{ item }}
  loop: "{{ dev_pyt_directories }}"
  register: acl_dirs
  failed_when: false
  ignore_errors: true
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

- name: Set default ACL rwx on directories (for future files/folders)
  command: setfacl -dR -m g:{{ dev_group_pyt }}:rwx {{ item }}
  loop: "{{ dev_pyt_directories }}"
  register: default_acl_dirs
  failed_when: false
  ignore_errors: true
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

- name: Set ACL rwx on individual files (optional)
  when: dev_pyt_files is defined and dev_pyt_files | length > 0
  command: setfacl -m g:{{ dev_group_pyt }}:rwx {{ item }}
  loop: "{{ dev_pyt_files }}"
  register: acl_files
  failed_when: false
  ignore_errors: true
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

- name: Display results for directories ACL set
  debug:
    msg: "Directory ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ acl_dirs.results }}"
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

- name: Display results for directories default ACL set
  debug:
    msg: "Default ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ default_acl_dirs.results }}"
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

- name: Display results for file ACL set
  when: dev_pyt_files is defined and dev_pyt_files | length > 0
  debug:
    msg: "File ACL applied to {{ item.item }}: {{ item.stdout if item.rc == 0 else item.stderr }}"
  loop: "{{ acl_files.results }}"
  tags: [vwdev_lpyt-sudoers, vwdev-lpyt_acl_implementation, system_preparation]

